platform :ios, '13.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MoodScape' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  # Enable modular headers for specific dependencies
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # Firebase Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/AnalyticsWithoutAdIdSupport'

  # Other dependencies
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true

  target 'MoodScapeTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
        config.build_settings['SWIFT_VERSION'] = '5.0'  # or the Swift version you are using
      end
    end

    # Custom settings for specific targets
    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          config.build_settings['OTHER_CFLAGS'] = ['-stdlib=libc++', '-std=c++14']
        end
      elsif target.name == 'GTMAppAuth'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  end
end
